.angular-build-dev:
  image: node:stable
  stage: build
  before_script:
    - npm config set depth 0
    - npm cache clean --force
  script:
    - npm install --no-progress
    - if [ -d "build" ]; then rm -rf build; fi
    - if [ -d "dist" ]; then rm -rf dist; fi
    - node_modules/.bin/ng build --aot --build-optimizer

.angular-build-prod:
  image: node:stable
  stage: build
  before_script:
    - npm config set depth 0
    - npm cache clean --force
  script:
    - npm install --no-progress
    - if [ -d "build" ]; then rm -rf build; fi
    - if [ -d "dist" ]; then rm -rf dist; fi
    - node_modules/.bin/ng build --prod --aot --build-optimizer
