.delivery-changelog:
  variables:
    GITLAB_CI_COMMONS: "gitlab-ci--commons"
  before_script:
    - cd ..
    - rm -rf ${CI_PROJECT_NAME}
    - git clone https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git
    - cd ${CI_PROJECT_NAME}
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - git config --global user.name "Service account"
  script:
    - rm -rf ../${GITLAB_CI_COMMONS}
    - git clone -b master --single-branch https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_NAMESPACE}/${GITLAB_CI_COMMONS}.git ../${GITLAB_CI_COMMONS}
    - git checkout develop
    - echo "Checking Changelog"
    - chmod +x ../${GITLAB_CI_COMMONS}/resources/changelog/changelog.sh
    - ../${GITLAB_CI_COMMONS}/resources/changelog/changelog.sh

.delivery-release:
  before_script:
    - cd ..
    - rm -rf ${CI_PROJECT_NAME}
    - git clone https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git
    - cd ${CI_PROJECT_NAME}
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - git config --global user.name "Service account"
  script:
    - git checkout master
    - git merge -Xtheirs develop
    - git tag ${RELEASE}
    - git push
    - git push origin ${RELEASE}